---
abstract: 'Build a table of contents from text documents'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  Test::More: 0.88
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-TOC
requires:
  File::Slurp: 0
  HTML::DOM: 0
  HTML::Entities: 0
  List::AllUtils: 0
  Moose: 0
  Moose::Role: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Params::Validate: 0
  MooseX::Role::Parameterized: 0
  MooseX::SemiAffordanceAccessor: 0
  MooseX::StrictConstructor: 0
  MooseX::Types: 0
  MooseX::Types::Combine: 0
  MooseX::Types::Moose: 0
  MooseX::Types::Path::Class: 0
  Path::Class: 0
  Tie::IxHash: 0
  base: 0
  namespace::autoclean: 0.12
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Text-TOC
  repository: git://git.urth.org/Text-TOC.git
version: 0.10
